### ISSUE TITLE
Metal Worm Gear Coupling - Possible to make from PETG?

### ISSUE THREAD

**Issue by terrag42** [bryancera/CERA-1#1]
I saw that the Shapeways price for the metal worm gear coupling was the same as for the Auger - $40. I wonder if a strong enough part can be made from PETG. I realize there is a lot of torque applied to this coupling, so perhaps instead of bolt it to a nut, one could file down a flat spot on the lead screw and design a part that  captures some M4 nuts in there, like in the attached screenshot:
![image](https://user-images.githubusercontent.com/9958086/78058844-e5529e00-7356-11ea-9b0a-902be544fb2b.png)
M4 grub screws could then be used to lock the lead screw to the coupling.

**Comment by bryancera** [comment]
Hi,

I appreciate this idea!

However, that is not quite how the coupler works.  You do not want to affix the leadscrew to the shaft, but rather the leadscrew nut.  The leadscrew nut is turned by the motor's hollow shaft, and this actually drives the leadscrew through the motor.

I have, however, printed a version in PETG, and one in PLA.  Unsurprisingly, it did not hold up to the nearly 300 pound-feet of torque applied to it at times during a print.  There's a good reason I decided to make this part in metal!  :D

**Comment by jeffnielson** [comment]
I still think there has to be an opportunity here, but I don't have enough experience with the printer to say where the failure will be.  For what it is worth, the vendor who is doing my steel print complained about possible failure points as detailed in the attached image.  When I printed in plastic, these were clearly potential issues as well.  Since the strain during printing isn't on that location, I don't think it'll be a problem, but I'm not going to make an suggestions until I have some experience with the machine.

![image-918](https://user-images.githubusercontent.com/5395344/79773948-1bed5a00-8300-11ea-8477-c11b04323ed6.png)

Thanks.

**Comment by gorborukov** [comment]
I use this part printed from ABS with fiberglass, it works successfully and withstands the load
